FROM bitnami/laravel:latest

WORKDIR /app

COPY . . 
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Ensure proper permissions for wait-for-it.sh
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 8000

# CMD ["./wait-for-it.sh", "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

